#
# JDBC Properties
#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_alfa?useSSL=false&serverTimezone=UTC
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

#
# General Properties
#
server:
  port: 8081